/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available modules with their tools */
        get: operations["listModules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available plans */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or find existing user from Clerk ID */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update user settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a user onboarding step */
        post: operations["completeUserOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get usage statistics */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get linked Stripe customer ID */
        get: operations["getStripeCustomerId"];
        /** Link a Stripe customer ID */
        put: operations["linkStripeCustomer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stored credentials */
        get: operations["listCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/credentials/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or update credentials for a module */
        put: operations["upsertCredential"];
        post?: never;
        /** Delete credentials for a module */
        delete: operations["deleteCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/apikeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys */
        get: operations["listApiKeys"];
        put?: never;
        /** Generate a new API key */
        post: operations["generateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/apikeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List prompts */
        get: operations["listPrompts"];
        put?: never;
        /** Create a prompt */
        post: operations["createPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a prompt by ID */
        get: operations["getPrompt"];
        /** Update a prompt */
        put: operations["updatePrompt"];
        post?: never;
        /** Delete a prompt */
        delete: operations["deletePrompt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/modules/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get module configuration */
        get: operations["getModuleConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/modules/{name}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update tool enable/disable settings for a module */
        put: operations["upsertToolSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/modules/{name}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update module description */
        put: operations["upsertModuleDescription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/oauth/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OAuth consents */
        get: operations["listOAuthConsents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/oauth/consents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an OAuth consent */
        delete: operations["revokeOAuthConsent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/apps/{provider}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OAuth app credentials for a provider */
        get: operations["getOAuthAppCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/oauth/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all OAuth apps (admin only) */
        get: operations["listOAuthApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/oauth/apps/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or update an OAuth app (admin only) */
        put: operations["upsertOAuthApp"];
        post?: never;
        /** Delete an OAuth app (admin only) */
        delete: operations["deleteOAuthApp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/apikeys/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if an API key is active (internal, called by Worker) */
        get: operations["getApiKeyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/oauth/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all OAuth consents across users (admin only) */
        get: operations["listAllOAuthConsents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        SuccessResult: {
            success: boolean;
        };
        PlanInfo: {
            id: string;
            name: string;
            daily_limit: number;
            price_monthly: number;
            stripe_price_id?: string | null;
            features?: {
                [key: string]: unknown;
            };
        };
        ModuleWithTools: {
            id: string;
            name: string;
            status: string;
            descriptions?: {
                [key: string]: string;
            };
            tools: unknown[];
        };
        ModuleConfig: {
            module_name: string;
            description?: string | null;
            tool_id: string;
            enabled: boolean;
        };
        UpsertToolSettingsBody: {
            enabled_tools: string[];
            disabled_tools: string[];
        };
        UpsertToolSettingsResult: {
            success: boolean;
            enabled_count?: number;
            disabled_count?: number;
        };
        UpsertModuleDescriptionBody: {
            description: string;
        };
        RegisterResult: {
            id: string;
        };
        UserProfile: {
            user_id: string;
            email: string;
            account_status: string;
            plan_id: string;
            daily_used: number;
            daily_limit: number;
            role: string;
            settings?: unknown;
            display_name?: string | null;
            connected_count: number;
        };
        UsageData: {
            total_used: number;
            by_module: {
                [key: string]: number;
            };
            period: components["schemas"]["UsagePeriod"];
        };
        UsagePeriod: {
            start: string;
            end: string;
        };
        UpdateSettingsBody: {
            settings: unknown;
        };
        CompleteOnboardingBody: {
            event_id: string;
        };
        OnboardingResult: {
            success: boolean;
            already_completed?: boolean;
            plan_id?: string;
            error?: string;
            message?: string;
        };
        StripeCustomer: {
            stripe_customer_id?: string | null;
        };
        LinkStripeCustomerBody: {
            stripe_customer_id: string;
        };
        Credential: {
            module: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpsertCredentialBody: {
            credentials: unknown;
        };
        UpsertCredentialResult: {
            success: boolean;
            module: string;
        };
        ApiKey: {
            id: string;
            key_prefix: string;
            display_name: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        GenerateApiKeyBody: {
            display_name: string;
            /**
             * Format: date-time
             * @description Expiration timestamp. If omitted, defaults to 90 days.
             */
            expires_at?: string;
            /** @description Set to true to create a key with no expiration. Overrides expires_at. */
            no_expiry?: boolean;
        };
        GenerateApiKeyResult: {
            /** @description Full API key (only returned at creation time) */
            api_key: string;
            key_prefix: string;
        };
        Prompt: {
            id: string;
            module_name?: string | null;
            name: string;
            description?: string | null;
            content: string;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GetPromptResult: {
            found: boolean;
            id?: string;
            module_name?: string | null;
            name?: string;
            description?: string | null;
            content?: string;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            error?: string;
        };
        CreatePromptBody: {
            name: string;
            content: string;
            module_name?: string;
            enabled: boolean;
            description?: string;
        };
        UpdatePromptBody: {
            name: string;
            content: string;
            module_name?: string;
            enabled: boolean;
            description?: string;
        };
        UpsertPromptResult: {
            success: boolean;
            id?: string;
            action?: string;
            error?: string;
        };
        DeletePromptResult: {
            success: boolean;
            error?: string;
        };
        OAuthAppCredentials: {
            provider?: string;
            client_id: string;
            client_secret: string;
            redirect_uri: string;
            error?: string;
            message?: string;
        };
        OAuthConsent: {
            id: string;
            client_id: string;
            client_name?: string | null;
            scopes: string;
            /** Format: date-time */
            granted_at: string;
        };
        OAuthConsentAdmin: {
            id: string;
            user_id: string;
            user_email?: string | null;
            client_id: string;
            client_name?: string | null;
            scopes: string;
            /** Format: date-time */
            granted_at: string;
        };
        RevokeConsentResult: {
            revoked?: boolean;
        };
        OAuthApp: {
            provider?: string;
            client_id?: string;
            redirect_uri?: string;
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        ApiKeyStatus: {
            /** @description Whether the API key is currently active */
            active: boolean;
            key_id: string;
            user_id: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        UpsertOAuthAppBody: {
            client_id: string;
            client_secret: string;
            redirect_uri: string;
            enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module list with tool definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleWithTools"][];
                };
            };
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanInfo"][];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User registered or already exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResult"];
                };
            };
            /** @description Missing clerk_id or email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsBody"];
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    completeUserOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOnboardingBody"];
            };
        };
        responses: {
            /** @description Onboarding step completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResult"];
                };
            };
        };
    };
    getUsage: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                start: string;
                /** @description End date (YYYY-MM-DD) */
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageData"];
                };
            };
        };
    };
    getStripeCustomerId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stripe customer info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeCustomer"];
                };
            };
        };
    };
    linkStripeCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkStripeCustomerBody"];
            };
        };
        responses: {
            /** @description Stripe customer linked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    listCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"][];
                };
            };
        };
    };
    upsertCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCredentialBody"];
            };
        };
        responses: {
            /** @description Credential saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertCredentialResult"];
                };
            };
        };
    };
    deleteCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"][];
                };
            };
        };
    };
    generateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateApiKeyBody"];
            };
        };
        responses: {
            /** @description Generated API key */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateApiKeyResult"];
                };
            };
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    listPrompts: {
        parameters: {
            query?: {
                /** @description Filter by module name */
                module?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"][];
                };
            };
        };
    };
    createPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromptBody"];
            };
        };
        responses: {
            /** @description Prompt created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertPromptResult"];
                };
            };
        };
    };
    getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPromptResult"];
                };
            };
        };
    };
    updatePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePromptBody"];
            };
        };
        responses: {
            /** @description Prompt updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertPromptResult"];
                };
            };
        };
    };
    deletePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePromptResult"];
                };
            };
        };
    };
    getModuleConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleConfig"][];
                };
            };
        };
    };
    upsertToolSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertToolSettingsBody"];
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertToolSettingsResult"];
                };
            };
        };
    };
    upsertModuleDescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertModuleDescriptionBody"];
            };
        };
        responses: {
            /** @description Description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    listOAuthConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth consent list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConsent"][];
                };
            };
        };
    };
    revokeOAuthConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consent revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeConsentResult"];
                };
            };
        };
    };
    getOAuthAppCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth app credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthAppCredentials"];
                };
            };
        };
    };
    listOAuthApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth app list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthApp"][];
                };
            };
        };
    };
    upsertOAuthApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertOAuthAppBody"];
            };
        };
        responses: {
            /** @description OAuth app saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    deleteOAuthApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth app deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResult"];
                };
            };
        };
    };
    getApiKeyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key UUID (kid claim from JWT) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyStatus"];
                };
            };
            /** @description API key not found or revoked */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAllOAuthConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All OAuth consents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConsentAdmin"][];
                };
            };
        };
    };
}
