#!/bin/bash
set -e

echo "=== MCPist Devcontainer Post-Create Setup ==="

# ----------------------------------------
# 0. Fix permissions
# ----------------------------------------
echo "[0/6] Fixing permissions..."
# Remove node_modules created on Windows host (permission issues)
# Use background process with timeout to avoid hanging
if [ -d /workspace/node_modules ]; then
    echo "Removing existing node_modules in background (this may take a while)..."
    # Start removal in background and continue - pnpm install will handle it
    (sudo rm -rf /workspace/node_modules 2>/dev/null &)
    sleep 2
fi
# Also clean nested node_modules in apps (background)
(sudo rm -rf /workspace/apps/*/node_modules 2>/dev/null &) || true
sleep 1
# Fix workspace permissions (skip node_modules to avoid delays)
echo "Fixing workspace permissions..."
sudo find /workspace -maxdepth 1 -not -name "node_modules" -exec chown -R vscode:vscode {} \; 2>/dev/null || true
sudo chown vscode:vscode /workspace
# Fix Go module cache permissions
sudo mkdir -p /home/vscode/go/pkg/mod/cache
sudo chown -R vscode:vscode /home/vscode/go

# ----------------------------------------
# 1. Install Node.js dependencies
# ----------------------------------------
echo "[1/6] Installing Node.js dependencies..."
cd /workspace
pnpm install

# ----------------------------------------
# 2. Install Go dependencies
# ----------------------------------------
echo "[2/6] Installing Go dependencies..."
cd /workspace/apps/server
go mod download

# ----------------------------------------
# 3. Wait for Docker (DinD)
# ----------------------------------------
echo "[3/6] Waiting for Docker daemon (DinD)..."
cd /workspace

timeout=60
while ! docker info >/dev/null 2>&1; do
    timeout=$((timeout - 1))
    if [ $timeout -le 0 ]; then
        echo "WARNING: Docker daemon not available after 60s"
        echo "You may need to restart the devcontainer or check DinD configuration"
        break
    fi
    sleep 1
done

if docker info >/dev/null 2>&1; then
    echo "Docker daemon is ready"
fi

# ----------------------------------------
# 4. Setup Supabase
# ----------------------------------------
echo "[4/6] Setting up Supabase..."

if docker info >/dev/null 2>&1; then
    echo "Starting Supabase (this may take a few minutes on first run)..."
    supabase start || echo "Supabase start failed, you may need to run it manually"

    # Extract Supabase keys
    if command -v supabase &> /dev/null; then
        ANON_KEY=$(supabase status --output json 2>/dev/null | jq -r '.ANON_KEY // empty')
        SERVICE_ROLE_KEY=$(supabase status --output json 2>/dev/null | jq -r '.SERVICE_ROLE_KEY // empty')
    fi
else
    echo "Skipping Supabase start (Docker not available)"
fi

# ----------------------------------------
# 5. Create .env.local if not exists
# ----------------------------------------
echo "[5/6] Setting up environment files..."

if [ ! -f /workspace/.env.local ]; then
    cat > /workspace/.env.local << EOF
# Local Development Environment
# Generated by post-create.sh

# Supabase
SUPABASE_URL=http://localhost:54321
SUPABASE_PUBLISHABLE_KEY=${ANON_KEY:-your-anon-key}

# API Endpoints (for Worker LB - Render Primary / Koyeb Failover)
RENDER_URL=http://localhost:8081
KOYEB_URL=http://localhost:8082

# Internal
INTERNAL_SERVICE_KEY=dev-internal-key

# Next.js
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY:-your-anon-key}
NEXT_PUBLIC_MCP_SERVER_URL=http://localhost:8787
EOF
    echo "Created .env.local"
    if [ -n "$ANON_KEY" ]; then
        echo "Supabase keys auto-populated from 'supabase status'"
    else
        echo "Please update Supabase keys manually"
    fi
fi

# ----------------------------------------
# 6. Create .env.traefik if not exists
# ----------------------------------------
echo "[6/6] Setting up Traefik environment..."

if [ ! -f /workspace/.env.traefik ]; then
    cat > /workspace/.env.traefik << 'EOF'
# Traefik Environment (for docker-compose.traefik.yml)
# Generated by post-create.sh

GATEWAY_SECRET=CvLog5KvMHz2GzUmQ3DGyJbBuKghDtoFniNpPKLLcT6zz9f86nxZsUvwmYke
SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0}
EOF
    echo "Created .env.traefik"
fi

# ----------------------------------------
# Done
# ----------------------------------------
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Development Modes:"
echo ""
echo "  1. Local Mode (pnpm dev):"
echo "     - Supabase:        http://localhost:54321"
echo "     - Supabase Studio: http://localhost:54323"
echo "     - Console:         http://localhost:3000"
echo "     - Server:          http://localhost:8089"
echo "     - Worker:          http://localhost:8787"
echo ""
echo "  2. Traefik Mode - Default (pnpm dev:traefik):"
echo "     - Console:         http://console.localhost"
echo "     - API:             http://api.localhost"
echo "     - MCP Gateway:     http://mcp.localhost"
echo "     - Dashboard:       http://localhost:8080"
echo ""
echo "  3. Traefik Mode - Infra (pnpm dev:traefik:infra):"
echo "     - Console:         http://console.localhost"
echo "     - API Primary:     http://api.localhost/primary/*"
echo "     - API Secondary:   http://api.localhost/secondary/*"
echo "     - MCP Gateway:     http://mcp.localhost"
echo "     - Dashboard:       http://localhost:8080"
echo ""
echo "  4. Legacy LB Testing (docker compose -f compose/api.yml up -d):"
echo "     - API Render:      http://localhost:8081"
echo "     - API Koyeb:       http://localhost:8082"
echo ""
