#!/bin/bash
set -e

echo "=== MCPist Devcontainer Post-Create Setup ==="

# ----------------------------------------
# 0. Fix permissions
# ----------------------------------------
echo "[0/5] Fixing permissions..."
# Remove node_modules created on Windows host (permission issues)
if [ -d /workspace/node_modules ]; then
    echo "Removing existing node_modules (fixing permission issues)..."
    sudo rm -rf /workspace/node_modules
fi
# Also clean nested node_modules in apps
sudo rm -rf /workspace/apps/*/node_modules 2>/dev/null || true
# Fix workspace permissions
sudo chown -R vscode:vscode /workspace
# Fix Go module cache permissions
sudo mkdir -p /home/vscode/go/pkg/mod/cache
sudo chown -R vscode:vscode /home/vscode/go

# ----------------------------------------
# 1. Install Node.js dependencies
# ----------------------------------------
echo "[1/5] Installing Node.js dependencies..."
cd /workspace
pnpm install

# ----------------------------------------
# 2. Install Go dependencies
# ----------------------------------------
echo "[2/5] Installing Go dependencies..."
cd /workspace/apps/server
go mod download

# ----------------------------------------
# 3. Wait for Docker (DinD)
# ----------------------------------------
echo "[3/5] Waiting for Docker daemon (DinD)..."
cd /workspace

timeout=60
while ! docker info >/dev/null 2>&1; do
    timeout=$((timeout - 1))
    if [ $timeout -le 0 ]; then
        echo "WARNING: Docker daemon not available after 60s"
        echo "You may need to restart the devcontainer or check DinD configuration"
        break
    fi
    sleep 1
done

if docker info >/dev/null 2>&1; then
    echo "Docker daemon is ready"
fi

# ----------------------------------------
# 4. Setup Supabase
# ----------------------------------------
echo "[4/5] Setting up Supabase..."

if docker info >/dev/null 2>&1; then
    echo "Starting Supabase (this may take a few minutes on first run)..."
    supabase start || echo "Supabase start failed, you may need to run it manually"

    # Extract Supabase keys
    if command -v supabase &> /dev/null; then
        ANON_KEY=$(supabase status --output json 2>/dev/null | jq -r '.ANON_KEY // empty')
        SERVICE_ROLE_KEY=$(supabase status --output json 2>/dev/null | jq -r '.SERVICE_ROLE_KEY // empty')
    fi
else
    echo "Skipping Supabase start (Docker not available)"
fi

# ----------------------------------------
# 5. Create .env.local if not exists
# ----------------------------------------
echo "[5/5] Setting up environment files..."

if [ ! -f /workspace/.env.local ]; then
    cat > /workspace/.env.local << EOF
# Local Development Environment
# Generated by post-create.sh

# Supabase
SUPABASE_URL=http://localhost:54321
SUPABASE_ANON_KEY=${ANON_KEY:-your-anon-key}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY:-your-service-role-key}

# API Endpoints (for Worker LB - Render Primary / Koyeb Failover)
RENDER_URL=http://localhost:8081
KOYEB_URL=http://localhost:8082

# Internal
INTERNAL_SERVICE_KEY=dev-internal-key

# Next.js
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY:-your-anon-key}
NEXT_PUBLIC_MCP_SERVER_URL=http://localhost:8787
EOF
    echo "Created .env.local"
    if [ -n "$ANON_KEY" ]; then
        echo "Supabase keys auto-populated from 'supabase status'"
    else
        echo "Please update Supabase keys manually"
    fi
fi

# ----------------------------------------
# Done
# ----------------------------------------
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Services available:"
echo "  - Supabase API:     http://localhost:54321"
echo "  - Supabase Studio:  http://localhost:54323"
echo "  - Next.js Console:  http://localhost:3000   (pnpm dev:console)"
echo "  - Go Server:        http://localhost:8089   (pnpm dev:server)"
echo "  - Worker:           http://localhost:8787   (pnpm dev:worker)"
echo ""
echo "LB Testing (Docker):"
echo "  - API Render:       http://localhost:8081   (docker compose -f compose/api.yml up -d)"
echo "  - API Koyeb:        http://localhost:8082"
echo ""
echo "Start all services: pnpm dev"
echo ""
